/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FavoriteResponse { 
    id: number;
    user_id: number;
    album_id: string;
    created_at: string;
    position: number;
}

