/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityFeedItemResponse } from './activityFeedItemResponse';


export interface ActivityFeedResponse { 
    items: Array<ActivityFeedItemResponse>;
}

