/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewFeedItemResponse } from './reviewFeedItemResponse';
import { UserPublicResponse } from './userPublicResponse';


export interface ActivityFeedItemResponse { 
    id: number;
    type: string;
    created_at: string;
    actor: UserPublicResponse;
    review?: ReviewFeedItemResponse | null;
    target_user?: UserPublicResponse | null;
}

