/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Artist } from './artist';


export interface Album { 
    id: number;
    title: string;
    cover?: string | null;
    artist: Artist;
}

