/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Album } from './album';


export interface FavoriteWithAlbumResponse { 
    id: number;
    user_id: number;
    album_id: string;
    position: number;
    created_at: string;
    album: Album;
}

