/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FavoriteItemInput } from './favoriteItemInput';


export interface FavoritesReplaceRequest { 
    favorites: Array<FavoriteItemInput>;
}

