/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPublicResponse } from './userPublicResponse';
import { Album } from './album';


export interface ReviewFeedItemResponse { 
    id: number;
    rating: number;
    content?: string | null;
    created_at: string;
    updated_at: string;
    album: Album;
    author: UserPublicResponse;
    likes_count?: number;
    liked_by_me?: boolean;
}

