/**
 * Wrapity
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Track { 
    id: number;
    title: string;
    duration: number;
    track_position?: number | null;
    disk_number?: number | null;
    preview?: string | null;
    explicit_lyrics?: boolean | null;
}

